### ISSUE TITLE
New TypeScript definition of 'patch' uses Buffer as a generic

### ISSUE THREAD

**Issue by MichalVasak** [bhousel/node-diff3#44]
Hi @bhousel 

This is a minor issue, but I use tsc --pretty in my pipeline and I started getting an error when building a project using the 2.1.1 version of node-diff3, so I have to stay on 2.1.0 until resolved:

"Type 'Buffer' is not generic."

for the new definition of patch in node-diff3/index.d.ts:

"export function patch<T>(buffer: T[], patch: IPatchRes<T>[]): Buffer<T>[];"

Thanks for making this very useful library!

**Comment by bhousel** [comment]
Ah, yeah I don't actually use TypeScript at all.  I basically just blindly accept any pull request involving the `indes.d.ts` file 👍

**Comment by MichalVasak** [comment]
Ok, I can see the issue, this is the actual line from index.d.ts (not sure why the messages show it as what I put in the original post instead):

    export function patch<T>(buffer: T[], patch: IPatchRes<T>[]): Buffer<T>[];

"Buffer<T>" is indeed an attempt to use Buffer as a generic. If the function truly returns an arrray of binary Buffer objects, the correct export would be:

    export function patch<T>(buffer: T[], patch: IPatchRes<T>[]): Buffer[];

If the function returns an array of type T, which seems more consistent with the other functions, it would be

    export function patch<T>(buffer: T[], patch: IPatchRes<T>[]): T[];

Happy to make the pull request if you want

**Comment by bhousel** [comment]
Thanks, I went with `T[]` as the return type.. Just published v2.1.2 with this fix 👍
