### ISSUE TITLE
Creating a merge of a three-way comparison

### ISSUE THREAD

**Issue by klablink** [bhousel/node-diff3#46]
Thanks for this great work. I am trying to compare 3 YAML files to create the merge using `diff3Merge`. As indicated in #45, I have tried using hunks, but I lose spaces and newlines; I assume because the separation is done using the regular expression `/\s+/.` I tried using` /\n/` to process line by line. Still, I get a false positive which I don't understand.  I use the below arguments:

o: 

```
title: "title"
description: "title"
```

a:

```
title: "title"
description: "title changed"
```

b:

```
title: "title changed"
description: "title"
```

result with `/\n/`:

```
[
    {
        "conflict": {
            "a": [
                "title": \{ "title",
                "description: \"title changed".
            ],
            "aIndex": 0,
            "o": [
                "title: \"title",
                "description: \"title""
            ],
            "oIndex": 0,
            "b": [
                "title: \"title changed\""
                "description: \"title""
            ],
            "bIndex": 0
        }
    },
    {
        "ok": [
            ""
        ]
    }
]

```

Whereas if I use `/s+/`: 

```
[
    {
        "ok": [
            "title:",
            "title",
            "changed",
            "description:",
            "title",
            "changed"",
            ""
        ]
    }
]
```

but losing the spaces and newlines. 

I expected to get as a result:

```
title: "title changed"
description: "title changed"
```

I don't understand if I'm doing something wrong or trying to use the library for a different purpose than the original one.

**Comment by bhousel** [comment]
Hey @klablink, sorry for the slow response.. It looks like you're using the library correctly but maybe the result isn't what you expected.  `diff3Merge` is correctly detecting that `o->a` and `o->b` has a conflict in that hunk.  It's up to you what to do about that conflict.  

This works the same as conflicts in git (which uses a similar diff algorithm).  The `Diff3.merge` function presents the results in a more git-style output (†sort of):

```js
    const r = Diff3.merge(a, o, b, { stringSeparator: /[\r\n]+/ });
    console.log(r.result.join('\n'));

<<<<<<<<< a
title: "title"
description: "description changed"
=========
title: "title changed"
description: "description"
>>>>>>>>> b

```

† When testing this issue I found that this library is still adding a bunch of `\n` into the diff output, and I think we should remove these and let the caller decide how to format these diff results.  (so the above example is not actually what it does yet).  I will open another issue for that.
